### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by zealot128** [dresden-weekly/ansible-rails#11]
Nice work so far!

I will try to add the following roles in the next couple of days/weeks :)

Sidekiq:
- start workers on system start
- start/restart worker gracefully on deploy
- Best place for this? upstart/sidekiq? or rails/sidekiq?

Cronjobs with whenever
- regenerate crontab for user with `whenever` (Gem I always use for managing cronjobs)
- Place? rails/whenever?

**Comment by arBmind** [comment]
Wow, so far your work looks very impressive.

We are working on using these roles into our production setup at HicknHack, since last week.
