### ISSUE TITLE
How to use the user jobs?

### ISSUE THREAD

**Issue by zealot128** [dresden-weekly/ansible-rails#22]
I have trouble setting up the user jobs.
Is there some sudo required for the running user to make it work? Didn't find any hints in a README or the puma template. I've included the upstart role with the regarding user as only argument in the users-list.

Starting the newly created job always results in:

```
$ start worker 
start: Unable to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

$ whoami
podfilter
```

(same with restart, stop)

Googling that error message always points out to use sudo - but that wouldn't work with the session_init type of user jobs?

---

contents of `~/.init/worker`:

``` upstart
# /etc/init/sidekiq.conf - Sidekiq config
# Ansible managed: /etc/ansible/roles/dresden-weekly.Rails/rails/jobs/sidekiq/templates/sidekiq.conf.j2 modified on 2015-09-29 21:38:51 by stefan on lnxhn04
description "Sidekiq Background podfilter"
start on user-jobs
stop on runlevel [06]
respawn
respawn limit 3 30
normal exit 0 TERM
reload signal USR1
instance /home/podfilter/app/current
script
exec /bin/bash <<'EOT'
  /bin/bash -lc -- '
    cd /var/www/app;
    exec bundle exec sidekiq -i 0 -e production -C /home/podfilter/app/shared/config/sidekiq.yml -L /home/podfilter/app/shared/log/sidekiq.log
  '
EOT
end script
```

Observations:
- Run file in /var/run/user/UID/upstart/sessions/SOMEID.session exists.
- the session_init and session_init_setup tasks are created, session_init is running with the USER argument:

```
# initctl list | grep session
session_init_setup stop/waiting
session_init (podfilter) start/running, process 9249
```
- File syntax of worker.conf is ok:

```
$ init-checkconf ~/.init/worker.conf
File worker.conf: syntax ok
```
- Ubuntu 14.04.3 with upstart installed

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
```

**Comment by zealot128** [comment]
nevermind - restarting the ssh session worked :dancers: 

Anyways; a Readme for the userjobs would be nice, i guess :) might be adding some with the Sidekiq role later on.

**Comment by arBmind** [comment]
More documentation is always a good thing... Sorry, for the inconvenience.
