### ISSUE TITLE
ansible-rails fails if the group name of the application is not "app"

### ISSUE THREAD

**Issue by tbraun89** [dresden-weekly/ansible-rails#32]
Following roles use the `groups` variable to get information about the application host:
- `nginx/puma`
- `nginx/webrick`
- `rails/create-release`
- `rails/publish-assets`

If the host has an other name this does not work:

```
TASK [dresden-weekly.Rails/nginx/webrick : Site configuration] *****************
fatal: [*********]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'app'"}
```

**Comment by arBmind** [comment]
This is currently part of the intended usage pattern. I guess we should add a configuration variable for this as well.
