### ISSUE TITLE
passenger_app_env in nginx configs?

### ISSUE THREAD

**Issue by vcavallo** [dresden-weekly/ansible-rails#61]
I was troubleshooting an issue where I'm deploying to a staging environment (I have `rails_env` set for staging) and found that passenger+nginx was attempting to use production. I ssh'd into the server and manually edited the `sites-available/[myapp].conf` to add:

```
passenger_app_env staging;
```

And now everything is working properly. Is this an nginx config that this role should be setting? Seems like it to me, but maybe I'm missing something. I'd be happy to attempt to add this in a PR, if desired.

Thanks for all your hard work!

**Comment by arBmind** [comment]
Take a look at the example project https://github.com/dresden-weekly/ansible-rails-example
The `app_user` should use a valid `.profile`

https://github.com/dresden-weekly/ansible-rails-example/blob/simple/ansible/plays/provision.yml
This includes the `RAILS_ENV`

**Comment by vcavallo** [comment]
As mentioned in my other comment - I realize that the `RAILS_ENV` variable is included properly, but what about the `passenger_app_env` line?

**Comment by arBmind** [comment]
This line is not needed. passenger uses the `app_user` and loads the profile. Worked perfectly for us so far.
If anything changed in passenger, let me know it.
