### ISSUE TITLE
Add support for --with option for bundler

### ISSUE THREAD

**Issue by mstarke** [dresden-weekly/ansible-rails#66]
The current setup only supports the ```--without``` option defaulted to ```test```and ```development```. Removing any of the defaults after the command has already been executed once with the defaults has no effect since those options are remembered as by ```bundle config```

Solutions to this might be an explicit ```--with``` support or to change the config to disable remembering of those values, if all invocations of ```bundle``` are coming from ansible.

**Comment by arBmind** [comment]
This is the intended behavior here.
