### ISSUE TITLE
Build is failing again

### ISSUE THREAD

**Issue by arBmind** [dresden-weekly/ansible-rails#83]
It seems the validation for RVM has changed again.

Before we can add any other changes this should be fixed.

**Comment by zealot128** [comment]
default key has changed:

```
rvm_gpg_keys: '7D2BAF1CF37B13E2069D6956105BD0E739499BDB 409B6B1796C275462A1703113804BB82D39DC0E3'
 rvm_gpg_key_server: 'hkp://keys.gnupg.net'
```

Unfortunately, our current mechanism to determine if the key is already available is to run gpg --list-keys. So, if the role is already run, that host cannot be fixed only with using Ansible DW Rails role, one has to start from scratch or manually enter and add the missing pubkey.

If run with both keys as argument, the command returns successfully also if only one of the keys is available. Maybe we might need to switch to a list and with_items .... to check for all keys?

**Comment by arBmind** [comment]
@zealot128 your code checks for both keys now? So this is fully resolved?

**Comment by zealot128** [comment]
Yes, AFAIK this should validate all current rvm installations.

**Comment by arBmind** [comment]
Very good! I will close this bug then.
